// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfegzvuuluptujaovesj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZWd6dnV1bHVwdHVqYW92ZXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjcyODMsImV4cCI6MjA2OTIwMzI4M30.TjgSacofHJPqjrpKGqGU5zp81Sib7ZIXsUCRFJI4jdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});